channels:
- conda-forge
- nodefaults
dependencies:
- aiohttp
- flox
- gsw-xarray
- lenapy
- openpyxl
- pip
- pwlf
- regionmask
- requests
- rioxarray
- statsmodels
- xarrayMannKendall
- pip:
  - git+https://github.com/ecjoliver/marineHeatWaves.git
  - pymannkendall
  - skillmetrics
